accessing
jsonWithNewData
	^ '{
        "userId" : "4e2085456a2943b6fb60efb3e645887a",
        "ideId" : "org.eclipse.platform_4.6.2.v20161124-1400 [557]",
        "eclipseProjects" : [
                {
                        "name" : "Donjon",
                        "executions" : [
                                { },
                                { },
                                { },
                                { },
                                { },
                                { },
                                { },
                                {
                                        "testClasses" : [
                                                {
                                                        "status" : "PASS",
                                                        "name" : "dungeon.AttackTest",
                                                        "duration" : -1.0,
                                                        "testMethods" : [
                                                                {
                                                                        "status" : "PASS",
                                                                        "name" : "testIsPossibleWhenMonstersInTheRoom",
                                                                        "duration" : 0.011999845504760742
                                                                }
                                                        ]
                                                }
                                        ],
                                        "endDate" : "Apr 6, 2017 2:57:13 PM",
                                        "scope" : "method",
                                        "governor" : "TestSelectionGovernorAtEachChange",
                                        "isSelectionPluginUsed" : true,
                                        "ideName" : "org.eclipse.platform_4.6.2.v20161124-1400 [557]",
                                        "type" : "junit",
                                        "id" : 11,
                                        "startDate" : "Apr 6, 2017 2:57:13 PM"
                                }
                        ],
                        "repoUrl" : [ ]
                }
        ]
}

'